{"variants":[{"paths":["\/documentation\/sotocore\/awsservererror\/context"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"kind":"symbol","abstract":[{"type":"text","text":"additional context information related to the error"}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"SotoCore"}],"symbolKind":"property","role":"symbol","title":"context","externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp"},"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"platforms":["Linux"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","url":"\/documentation\/sotocore","kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","role":"collection","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"title":"AWSServerError","navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"url":"\/documentation\/sotocore\/awsservererror","type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"kind":"symbol","title":"AWSErrorContext","navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","role":"symbol","type":"topic","abstract":[{"text":"Additional information about error","type":"text"}],"url":"\/documentation\/sotocore\/awserrorcontext","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSErrorContext"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"kind":"symbol","title":"context","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","role":"symbol","type":"topic","abstract":[{"text":"additional context information related to the error","type":"text"}],"url":"\/documentation\/sotocore\/awsservererror\/context","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext"},{"kind":"text","text":"?"}]}}}