{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/context"]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"kind":"symbol","abstract":[{"text":"additional context information related to the error","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"platforms":["Linux"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"SotoCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","kind":"typeIdentifier","text":"AWSErrorContext"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","symbolKind":"property","title":"context"},"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}],"type":"topic","url":"\/documentation\/sotocore\/awsservererror","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","title":"AWSServerError","navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","url":"\/documentation\/sotocore","role":"collection","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","title":"SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}],"type":"topic","url":"\/documentation\/sotocore\/awserrorcontext","role":"symbol","abstract":[{"text":"Additional information about error","type":"text"}],"kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","title":"AWSErrorContext","navigatorTitle":[{"text":"AWSErrorContext","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"type":"text","text":"additional context information related to the error"}],"url":"\/documentation\/sotocore\/awsservererror\/context","kind":"symbol","role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","title":"context"}}}