{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SotoCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","role":"symbol","roleHeading":"Instance Property","title":"context","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/context"]}],"sections":[],"abstract":[{"text":"additional context information related to the error","type":"text"}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"url":"\/documentation\/sotocore\/awserrorcontext","title":"AWSErrorContext","navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"type":"topic","abstract":[{"text":"Additional information about error","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"AWSErrorContext","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","role":"collection","kind":"symbol","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","title":"AWSServerError","abstract":[],"type":"topic","url":"\/documentation\/sotocore\/awsservererror","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}],"navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"url":"\/documentation\/sotocore\/awsservererror\/context","role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context","abstract":[{"text":"additional context information related to the error","type":"text"}],"title":"context","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"context"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic"}}}