{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/internalfailure"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWSServerError","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Linux"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWSServerError","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"}],"externalID":"s:8SotoCore14AWSServerErrorV15internalFailureACvpZ","title":"internalFailure","role":"symbol","roleHeading":"Type Property","symbolKind":"property","modules":[{"name":"SotoCore"}]},"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}],"kind":"symbol","title":"AWSServerError","navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/sotocore\/awsservererror","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/internalFailure":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/sotocore\/awsservererror\/internalfailure","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","title":"internalFailure","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalFailure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSServerError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"}],"abstract":[]},"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","kind":"symbol","role":"collection","url":"\/documentation\/sotocore","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore"}}}