{"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure"},"metadata":{"title":"internalFailure","externalID":"s:8SotoCore14AWSServerErrorV15internalFailureACvpZ","roleHeading":"Type Property","modules":[{"name":"SotoCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalFailure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWSServerError","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Linux"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/internalfailure"]}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"role":"collection","url":"\/documentation\/sotocore","kind":"symbol","title":"SotoCore","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"title":"AWSServerError","url":"\/documentation\/sotocore\/awsservererror","type":"topic","abstract":[],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSServerError"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/internalFailure":{"kind":"symbol","url":"\/documentation\/sotocore\/awsservererror\/internalfailure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError"}],"role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","title":"internalFailure","type":"topic","abstract":[]}}}