{"kind":"symbol","variants":[{"paths":["\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waiterFailed"},{"kind":"text","text":": "},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","kind":"typeIdentifier","text":"ClientError"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["Linux"]}]}],"sections":[],"abstract":[{"type":"text","text":"Waiter failed, but without an error. ie a successful api call was an error"}],"metadata":{"externalID":"s:8SotoCore9AWSClientC11ClientErrorV12waiterFailedAEvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiterFailed","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ClientError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV"}],"modules":[{"name":"SotoCore"}],"roleHeading":"Type Property","symbolKind":"property","role":"symbol","title":"waiterFailed"},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError"]]},"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"url":"\/documentation\/sotocore","title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","type":"topic","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"role":"collection","kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient":{"type":"topic","kind":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient","abstract":[{"type":"text","text":"Client managing communication with AWS services"}],"url":"\/documentation\/sotocore\/awsclient","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSClient"}],"title":"AWSClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSClient"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientError"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError","url":"\/documentation\/sotocore\/awsclient\/clienterror","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ClientError"}],"abstract":[{"text":"Errors returned by ","type":"text"},{"type":"codeVoice","code":"AWSClient"},{"text":" code","type":"text"}],"role":"symbol","title":"AWSClient.ClientError"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSClient/ClientError/waiterFailed":{"title":"waiterFailed","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSClient\/ClientError\/waiterFailed","url":"\/documentation\/sotocore\/awsclient\/clienterror\/waiterfailed","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waiterFailed","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore9AWSClientC11ClientErrorV","text":"ClientError","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Waiter failed, but without an error. ie a successful api call was an error"}],"role":"symbol","kind":"symbol"}}}